# -*- coding: utf-8 -*-
"""Task-9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPXhOVajUZE1bxK4RvvP2pDZ6ybRQm4x
"""

import numpy as np
import sympy as sp


class Task9:
    def __init__(self) -> None:
        pass

    def generate(self):
        x, y, z, t = sp.symbols('x y z t')
        while True:
            while True:
              A = sp.Point(np.random.randint(-15, 15),
                          np.random.randint(-15, 15),
                          np.random.randint(-15, 15))
              if A.x != 0 and A.y !=0 and A.z != 0:
                break

            while True:
                LP = sp.Point(np.random.randint(-15, 15),
                              np.random.randint(-15, 15),
                              np.random.randint(-15, 15))
                if A.x != LP.x and A.y != LP.y:
                  break
            


            A0 = sp.Point3D(2*LP.x - A.x, 2*LP.y - A.y, 2*LP.z - A.z)

            AA0 = sp.Segment(A, A0) # отрезок из точки А и точки которую нужно найти

            L = AA0.perpendicular_line(LP) # прямая перпендикулярная к AA0
            l_eq = L.equation(x,y,z) # уравнение L 

            while True:
                x1, y2 = np.random.randint(-3, 3), np.random.randint(-3, 3)
                s1 = sp.solve(l_eq.subs(x, x1))
                s2 = sp.solve(l_eq.subs(y, y2))
                y1,z1 = s1[y], s1[z]
                x2,z2 = s2[x], s2[z]
                
                M1 = sp.Point(x1,y1,z1)
                M2 = sp.Point(x2,y2,z2)
            
                if M1 != M2:
                    break
            
            if M1.x == int(M1.x) and M2.x == int(M2.x) and M1.y == int(M1.y) and M2.y == int(M2.y) and M1.z == int(M1.z) and M2.z == int(M2.z):
              break


        task_text = f'Даны точки $A({A.x}, \\,{A.y}, \\,{A.z})$, ' \
                    f'$M_1({M1.x}, \\,{M1.y}, \\,{M1.z})$, ' \
                    f'$M_2({M2.x}, \\,{M2.y}, \\,{M2.z})$. ' \
                    'Написать каноническое уравнение прямой $L$, проходящей через точки $M_1$ и $M_2$. ' \
                    'Найти координаты точки $A_0$, расположенной симметрично точки $A$ относительно прямой $L$.'

        answer_text = '\\renewcommand{\\arraystretch}{2.5} $$ ' \
                      + f'L: \\frac{{ {x - M1.x} }}{{ {M2.x - M1.x} }} = ' \
                        f'\\frac{{ {y - M1.y} }}{{ {M2.y - M1.y} }} = ' \
                        f'\\frac{{ {z - M1.z} }}{{ {M2.z - M1.z} }} $$ $$' \
                        f'A_0 = \\left( {sp.latex(A0.x)}, \\,{sp.latex(A0.y)}, \\,{sp.latex(A0.z)} \\right)' \
                          .replace('frac', 'dfrac') \
                          .replace('\\left(\\begin{matrix}', '\\begin{pmatrix}') \
                          .replace('\\end{matrix}\\right)', '\\end{pmatrix}') \
                      + ' $$ \\renewcommand{\\arraystretch}{1}'

        return task_text, answer_text